const { chromium } = require(process.env.PLAYWRIGHT_PATH || 'playwright');
const assert = require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const output=process.env.TEST_OUTPUT_DIR || path.resolve(__dirname,'../test-results');fs.mkdirSync(output,{recursive:true});
const artifact=name=>path.join(output,name);
const KEY='zheying.save.v2';
const BASE=process.env.GAME_URL||'http://127.0.0.1:8765';
(async()=>{
 const browser=await chromium.launch({channel:'chrome',headless:true});
 const context=await browser.newContext({viewport:{width:1440,height:960},reducedMotion:'reduce'});
 await context.addInitScript(()=>{const Native=window.AudioContext;window.__audio=[];if(Native)window.AudioContext=class extends Native{constructor(...args){super(...args);const entry={ctx:this,gains:[]};window.__audio.push(entry);const gain=this.createGain.bind(this);this.createGain=()=>{const g=gain();entry.gains.push(g);return g;};const compressor=this.createDynamicsCompressor.bind(this);this.createDynamicsCompressor=()=>{const c=compressor();entry.analyser=this.createAnalyser();c.connect(entry.analyser);return c;};}};});
 const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 page.setDefaultTimeout(7000);
 const snapshot=async()=>page.evaluate(key=>JSON.parse(localStorage.getItem(key)),KEY);
 const click=async selector=>{await page.locator(selector).click();};
 const press=async(selector,key,n=1)=>{for(let i=0;i<n;i++){await page.locator(selector).focus();await page.keyboard.press(key);}};
 const point=async(x,y)=>page.evaluate(({x,y})=>{const s=document.querySelector('#stage'),p=s.createSVGPoint();p.x=x;p.y=y;const t=p.matrixTransform(s.getScreenCTM());return {x:t.x,y:t.y};},{x,y});
 const drag=async(x,y,dx,dy)=>{const a=await point(x,y),b=await point(x+dx,y+dy);await page.mouse.move(a.x,a.y);await page.mouse.down();await page.mouse.move(b.x,b.y,{steps:8});await page.mouse.up();};
 const enter=async i=>{await click(`[data-room="${i}"]`);assert.equal((await snapshot()).scene,i);};
 const back=async()=>click('#return-room');
 await page.goto(BASE);
 await page.screenshot({animations:'disabled',path:artifact('title.png')});
 await click('#sound');await click('#start');
 assert.equal((await snapshot()).muted,true);
 await page.screenshot({animations:'disabled',path:artifact('room.png')});
 await click('[data-room="3"]');assert.equal((await snapshot()).scene,'room');
 await enter(0);await page.screenshot({animations:'disabled',path:artifact('puzzle-1.png')});
 await click('#hint');await click('#next-hint');await click('#next-hint');assert.equal(await page.locator('.hint-step').count(),3);await click('#close-panel');
 await drag(455,270,0,40);assert.deepEqual((await snapshot()).puzzles[0].offsets,[-40,80]);
 await page.reload();await click('#start');assert.equal((await snapshot()).scene,0);assert.deepEqual((await snapshot()).puzzles[0].offsets,[-40,80]);
 await click('#reset');assert.deepEqual((await snapshot()).puzzles[0].offsets,[-80,80]);
 // Escape cancels an in-progress drag without corrupting the checkpoint.
 const a=await point(455,270),b=await point(455,310);await page.mouse.move(a.x,a.y);await page.mouse.down();await page.mouse.move(b.x,b.y);await page.keyboard.press('Escape');await page.mouse.up();assert.deepEqual((await snapshot()).puzzles[0].offsets,[-80,80]);
 await drag(455,270,0,80);assert.equal((await snapshot()).solved[0],false);await drag(744,415,0,-80);assert.equal((await snapshot()).solved[0],true);await back();
 await enter(1);await page.screenshot({animations:'disabled',path:artifact('puzzle-2.png')});
 await drag(442,350,0,-80);await drag(568,340,0,60);await drag(747,370,0,-20);assert.equal((await snapshot()).solved[1],true);await page.screenshot({animations:'disabled',path:artifact('puzzle-2-solved.png')});await back();
 await enter(2);await page.screenshot({animations:'disabled',path:artifact('puzzle-3.png')});
 // Use central painted pivots; the wings themselves overlap, as paper should.
 for(const [i,n] of [[0,3],[1,1],[2,2]])await press(`[data-turn="${i}"]`,'Enter',n);
 assert.equal((await snapshot()).solved[2],true);await page.screenshot({animations:'disabled',path:artifact('puzzle-3-solved.png')});await back();
 await enter(3);await page.screenshot({animations:'disabled',path:artifact('puzzle-4.png')});
 await click('[data-symbol="0"]');await click('[data-symbol="1"]');await click('[data-symbol="2"]');assert.equal((await snapshot()).solved[3],false);await click('[data-clear]');
 await drag(500,480,100,0);await drag(920,400,0,-80);assert.deepEqual((await snapshot()).puzzles[3].offsets,[0,0]);
 await page.screenshot({animations:'disabled',path:artifact('puzzle-4-aligned.png')});
 await click('[data-symbol="1"]');await click('[data-symbol="0"]');await click('[data-symbol="2"]');assert.equal((await snapshot()).solved[3],false);
 await click('[data-symbol="0"]');await click('[data-symbol="1"]');await click('[data-symbol="2"]');assert.equal((await snapshot()).solved[3],true);await back();
 await enter(4);await page.screenshot({animations:'disabled',path:artifact('puzzle-5.png')});
 await drag(400,267,140,0);await drag(540,267,280,0);await drag(680,267,140,0);assert.equal((await snapshot()).solved[4],true);await page.screenshot({animations:'disabled',path:artifact('puzzle-5-solved.png')});await back();
 await enter(5);await page.screenshot({animations:'disabled',path:artifact('puzzle-6.png')});
 await click('[data-fold="0"]');assert.equal((await snapshot()).solved[5],false);await click('[data-fold="1"]');assert.equal((await snapshot()).solved[5],true);await page.screenshot({animations:'disabled',path:artifact('puzzle-6-solved.png')});await back();
 await page.screenshot({animations:'disabled',path:artifact('puzzle-7.png')});
 // Test both outward dragging and clicking the final paper corners.
 await drag(225,99,-55,-55);
 for(const [x,y] of [[966,90],[1015,596],[207,603]]){const p=await point(x,y);await page.mouse.click(p.x,p.y);}
 assert.equal((await snapshot()).solved.slice(0,7).every(Boolean),true);assert.equal((await snapshot()).solved[7],false);assert.equal((await snapshot()).scene,'room');assert.equal((await snapshot()).roomView,1);assert.equal(await page.locator('#ending').isVisible(),false);
 await page.screenshot({animations:'disabled',path:artifact('expanded-room.png')});
 await click('[data-pan="0"]');assert.equal((await snapshot()).roomView,0);await click('[data-pan="1"]');
 const exp=async(op,a=0,b=1,n=1)=>{for(let k=0;k<n;k++)await click(`[data-exp="${op}"][data-a="${a}"][data-b="${b}"]`);};
 const pick=async slot=>click(`[data-exp="pick"][data-a="${slot}"]`);
 const sort=async(i,target)=>{for(let s=0;s<target.length;s++){const p=(await snapshot()).puzzles[i],from=p.order.indexOf(target[s]);if(from!==s){await pick(from);await pick(s);}}};
 await enter(7);await page.screenshot({animations:'disabled',path:artifact('puzzle-8.png')});
 await click('#hint');await click('#next-hint');await click('#next-hint');await click('#close-panel');
 await drag(365,265,140,0);assert.deepEqual((await snapshot()).puzzles[7].order,[2,4,0,5,1,3]);await click('#undo');assert.deepEqual((await snapshot()).puzzles[7].order,[4,2,0,5,1,3]);
 const a8=await point(365,265),b8=await point(500,260);await page.mouse.move(a8.x,a8.y);await page.mouse.down();await page.mouse.move(b8.x,b8.y);await page.keyboard.press('Escape');await page.mouse.up();assert.deepEqual((await snapshot()).puzzles[7].order,[4,2,0,5,1,3]);
 await sort(7,[0,1,2,3,4,5]);
 for(let id=0;id<6;id++){await pick(id);const n=(4-(await snapshot()).puzzles[7].turns[id])%4;await exp('turn',id,1,n);if(id<5)await pick(id);}
 assert.equal((await snapshot()).solved[7],true);await page.screenshot({animations:'disabled',path:artifact('puzzle-8-solved.png')});await back();
 await enter(8);await page.screenshot({animations:'disabled',path:artifact('puzzle-9.png')});
 await exp('angle',0,1,2);for(const [id,n] of [[0,3],[1,1],[2,2]])await exp('turn',id,1,n);assert.equal((await snapshot()).solved[8],false);for(const [id,n] of [[0,1],[1,2],[2,1]])await exp('slide',id,1,n);
 assert.equal((await snapshot()).solved[8],true);await page.screenshot({animations:'disabled',path:artifact('puzzle-9-solved.png')});await back();
 await enter(9);await page.screenshot({animations:'disabled',path:artifact('puzzle-10.png')});await drag(335,606,110,0);assert.deepEqual((await snapshot()).puzzles[9].order,[1,0,2,3]);await click('#undo');await sort(9,[2,0,3,1]);assert.equal((await snapshot()).solved[9],false);
 await pick(2);await exp('flip',3);await pick(2);await pick(3);await exp('flip',1);assert.equal((await snapshot()).solved[9],true);await page.screenshot({animations:'disabled',path:artifact('puzzle-10-solved.png')});await back();
 await enter(10);await page.screenshot({animations:'disabled',path:artifact('puzzle-11.png')});
 const boardPoint=cell=>[433+(cell%3-Math.floor(cell/3))*70,426+(cell%3+Math.floor(cell/3)-2)*40];
 for(const [id,to] of [[1,5],[0,0],[2,6],[3,8]]) {const from=(await snapshot()).puzzles[10].positions[id],[x,y]=boardPoint(from),[xx,yy]=boardPoint(to);await drag(x,y,xx-x,yy-y);}
 assert.equal((await snapshot()).solved[10],true);await page.screenshot({animations:'disabled',path:artifact('puzzle-11-solved.png')});await back();
 await enter(11);await page.screenshot({animations:'disabled',path:artifact('puzzle-12.png')});for(const [id,n] of [[0,2],[1,7],[2,4]])await exp('ring',id,1,n);assert.equal((await snapshot()).solved[11],true);await page.screenshot({animations:'disabled',path:artifact('puzzle-12-solved.png')});await back();
 await enter(12);await page.screenshot({animations:'disabled',path:artifact('puzzle-13.png')});
 await exp('back',0,0);assert.equal((await snapshot()).puzzles[12].back,true);await exp('back',0,0);
 await exp('fold','left',0);await exp('fold','bottom',0);await page.reload();await click('#start');assert.equal((await snapshot()).scene,12);assert.deepEqual((await snapshot()).puzzles[12].sequence,['left','bottom']);await click('#undo');assert.deepEqual((await snapshot()).puzzles[12].sequence,['left']);await exp('fold','bottom',0);await exp('fold','right',0);await exp('fold','top',0);assert.equal((await snapshot()).solved[12],true);await page.screenshot({animations:'disabled',path:artifact('puzzle-13-solved.png')});await back();
 await enter(13);await page.screenshot({animations:'disabled',path:artifact('puzzle-14.png')});
 for(let i=0;i<4;i++)await exp('wall',i,1,2);assert.equal((await snapshot()).solved[13],false);await exp('window',0,1,2);assert.equal((await snapshot()).solved.every(Boolean),true);
 await page.screenshot({animations:'disabled',path:artifact('puzzle-14-solved.png')});await page.locator('#ending').waitFor({state:'visible'});await page.screenshot({animations:'disabled',path:artifact('ending-v2.png')});
 await page.reload();await click('#start');assert.equal(await page.locator('#ending').isVisible(),true);
 await click('#ending-room');
 // Audio settings use actual keyboard input, independent buses, and persisted values.
 await click('#menu');await click('#settings-menu');await click('#settings-mute');
 const range=async(id,n)=>{await page.locator('#'+id).focus();await page.keyboard.press('Home');for(let k=0;k<n;k++)await page.keyboard.press('ArrowRight');};
 await range('music-volume',18);await range('effects-volume',92);await click('#sound-preview');
 await page.screenshot({animations:'disabled',path:artifact('audio-settings.png')});
 const audio=await page.evaluate(()=>window.__audio.map(a=>({state:a.ctx.state,gains:a.gains.slice(0,3).map(g=>g.gain.value)})));
 assert.equal(audio[0].state,'running');assert.equal((await snapshot()).musicVolume,.18);assert.equal((await snapshot()).effectsVolume,.92);
 const rms=async()=>page.evaluate(async()=>{const a=window.__audio[0].analyser,b=new Float32Array(a.fftSize);let peak=0;for(let i=0;i<16;i++){await new Promise(requestAnimationFrame);a.getFloatTimeDomainData(b);peak=Math.max(peak,Math.sqrt(b.reduce((n,v)=>n+v*v,0)/b.length));}return peak;});
 const audible=await rms();assert.ok(audible>.001,'audio output must have a measurable signal');
 await click('#settings-mute');await page.waitForTimeout(800);assert.ok((await rms())<.0001,'mute must silence both buses');await click('#close-panel');
 await page.reload();await click('#start');assert.equal((await snapshot()).musicVolume,.18);assert.equal((await snapshot()).effectsVolume,.92);assert.equal((await snapshot()).muted,true);
 // Migration is seeded before app startup, so the previous page cannot overwrite it on pagehide.
 const legacy={version:1,started:true,scene:'ending',puzzles:[{offsets:[0,0]},{offsets:[0,0,0]},{turns:[0,0,0]},{offsets:[0,0],input:[0,1,2]},{order:[0,1,2,3]},{folds:[true,true]},{corners:[true,true,true,true]}],solved:Array(7).fill(true),hints:Array(7).fill(2),muted:true};
 const migrationContext=await browser.newContext();await migrationContext.addInitScript(s=>localStorage.setItem('zheying.save.v1',JSON.stringify(s)),legacy);const migration=await migrationContext.newPage();await migration.goto(BASE);await migration.locator('#start').click();await migration.locator('[data-room="7"]').click();assert.equal(await migration.locator('#scene-title').textContent(),'留白生枝');assert.equal(await migration.evaluate(()=>JSON.parse(localStorage.getItem('zheying.save.v1')).version),1);await migrationContext.close();
 await click('#menu');await click('#restart-menu');await click('#cancel-restart');assert.equal((await snapshot()).solved.every(Boolean),true);
 await click('#menu');await click('#restart-menu');await click('#confirm-restart');assert.equal((await snapshot()).solved.some(Boolean),false);assert.equal((await snapshot()).musicVolume,.18);assert.equal(await page.locator('#intro').isVisible(),true);
 const corrupt=await context.newPage();await corrupt.addInitScript(k=>localStorage.setItem(k,'bad json'),KEY);await corrupt.goto(BASE);await corrupt.locator('#start').click();await corrupt.locator('[data-room="0"]').click();assert.equal(await corrupt.locator('#scene-title').textContent(),'窗缝');await corrupt.close();
 const blocked=await context.newPage();await blocked.addInitScript(()=>{Storage.prototype.getItem=function(){return null;};Storage.prototype.setItem=function(){throw new Error('storage denied');};});await blocked.goto(BASE);await blocked.locator('#start').click();await blocked.locator('[data-room="0"]').click();assert.match(await blocked.locator('#save-status').textContent(),/存档不可用/);await blocked.close();
 const offline=await context.newPage();await offline.goto('file://' + path.resolve(__dirname,'../index.html'));await offline.locator('#start').click();await offline.locator('[data-room="0"]').click();assert.equal(await offline.locator('#scene-title').textContent(),'窗缝');await offline.close();
 assert.deepEqual(errors,[]);
 fs.writeFileSync(artifact('browser-results-v2.json'),JSON.stringify({url:BASE,browser:await browser.version(),passed:true,consoleErrors:errors,audio:{audibleRms:audible,settings:audio},checks:['fourteen-puzzle real browser playthrough','chapter 7 expands without ending','two room views','three hints','mouse dragging and cancelled drag','undo and reset','fold checkpoint and undo after refresh','both projections required','v1 migration without changing old save','v2 ending refresh','audio independently configurable','audio output and mute','volume persistence','restart confirmation','corrupt save recovery','storage unavailable','file URL entry']},null,2));
 console.log('PASS: fourteen puzzles, room expansion, save migration, settings and audible/muted audio.');await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});
