const assert = require('node:assert/strict');
const L = require('../logic.js');
const win = [{offsets:[0,0]},{offsets:[0,0,0]},{turns:[0,0,0]},{offsets:[0,0],input:[0,1,2]},{order:[0,1,2,3]},{folds:[true,true]},{corners:[true,true,true,true]}];
L.initial.forEach((p,i)=>assert.equal(L.isSolved(i,p),false,`initial puzzle ${i+1}`));
win.forEach((p,i)=>assert.equal(L.isSolved(i,p),true,`solution ${i+1}`));
assert.equal(L.isSolved(1,{offsets:[40,40,40]}),true,'equivalent aligned bird is accepted');
assert.equal(L.isSolved(1,{offsets:[0,0,20]}),false,'broken bird is rejected');
assert.equal(L.isSolved(0,{offsets:[40,40]}),false,'circle must meet visible window marks');
assert.equal(L.isSolved(3,{offsets:[0,40],input:[0,1,2]}),false,'correct symbols alone cannot bypass paper alignment');
assert.equal(L.isSolved(3,{offsets:[0,0],input:[1,0,2]}),false,'incorrect symbol sequence rejected');
const perms = xs => xs.length ? xs.flatMap((x,i)=>perms(xs.filter((_,k)=>k!==i)).map(p=>[x,...p])) : [[]];
assert.equal(perms([0,1,2,3]).filter(order=>L.isSolved(4,{order})).length,1,'exactly one connected shadow route');
let mirror=0;for(let a=0;a<4;a++)for(let b=0;b<4;b++)for(let c=0;c<4;c++)mirror+=L.isSolved(2,{turns:[a,b,c]});
assert.equal(mirror,1,'exactly one connected set of wings');
for(const invalid of [null,{},42,{version:9}, {...L.fresh(),puzzles:[]}])assert.deepEqual(L.restore(invalid),L.fresh());
const complete = L.fresh();complete.started=true;complete.puzzles=win;complete.solved.fill(true);complete.scene='ending';
assert.deepEqual(L.restore(complete),complete,'completed game survives restore');
const corrupt=L.fresh();corrupt.puzzles[4].order=[0,0,1,2];assert.deepEqual(L.restore(corrupt),L.fresh());
const bypass=L.fresh();bypass.solved.fill(true);bypass.scene=5;assert.equal(L.restore(bypass).scene,'room');assert.equal(L.restore(bypass).solved.some(Boolean),false);
console.log('PASS: initial/winning/wrong states, all 24 shadow permutations, all 64 mirror rotations, equivalent solutions and save validation.');
